name: Post welcome comment
on:
  pull_request:
    types: [opened]
  push:
    branches:
      - 'jfrog-integration'
permissions:
  pull-requests: write
jobs:
  build:
    name: Setup Artifactory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        id: download
        with:
          name: 'my-artifact'
          path: path/to/artifacts

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
      - uses: jfrog/setup-jfrog-cli@v3
        env:
          # JFrog platform url (for example: https://acme.jfrog.io) 
          JF_URL: ${{ secrets.JF_URL }}
          # Basic authentication credentials
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
      - run: |
          # Ping the server
          jf rt ping
          #jf rt u README.md default-generic-local/README.md
          
